// Fichas de los motores: qué hace cada uno (para elegir motor) y el formulario de sus funciones (rules).
// El panel arma el editor "Funciones del motor" con estos campos; así cada función nueva de un motor es editable
// sin tocar JSON. Tipos de campo (t):
//   int / num      número (min, max, step)          pct   probabilidad 0..1 que se muestra en %
//   bool           sí / no                           select  opciones o: [[valor, etiqueta]]
//   text           texto                             list  lista de números separados por coma
//   kv             mapa número → número (ej. scatters → giros; kl/vl = títulos de columnas)
//   table          lista de filas con columnas cols: [{ k, l, t, … }]
// k es la ruta dentro de rules (con puntos para anidar: "bonusMenu.wheel.spins"). g agrupa los campos.
// nullable: el campo se puede dejar vacío (null = función apagada).

const MAXWIN = { k: 'maxWin', l: 'Premio máximo (× la apuesta)', t: 'int', min: 100, max: 100000, g: 'General', help: 'Tope de premio por ronda.' };
const BUY = (help = 'Vacío = sin compra. El precio se recalcula al pulsar «Ajustar RTP».') => ({ k: 'buyCost', l: 'Precio de compra de giros gratis (× la apuesta)', t: 'num', min: 1, max: 1000, step: 0.1, nullable: true, g: 'Compra', help });
const ANTE = [
  { k: 'anteCost', l: 'Precio de la doble chance (× la apuesta)', t: 'num', min: 0, max: 5, step: 0.01, nullable: true, g: 'Doble chance', help: 'Vacío o 0 = sin doble chance. El precio se recalcula con «Ajustar RTP».' },
  { k: 'anteScatterChance', l: 'Probabilidad extra de scatter por casilla', t: 'pct', min: 0, max: 0.2, step: 0.001, g: 'Doble chance' },
];
const WEIGHTED = (k, l, g, extra = [], help) => ({ k, l, t: 'table', g, help, cols: [...extra, { k: 'weight', l: 'Peso', t: 'num', min: 0.01, step: 0.01 }] });
const MULTS = (k = 'multiplierValues', l = 'Multiplicadores posibles', g = 'Multiplicadores') => WEIGHTED(k, l, g, [{ k: 'value', l: 'Valor ×', t: 'num', min: 1, step: 1 }]);

export const RULE_SCHEMAS = {
  'reel-rush': [
    { k: 'cascadeMultipliers', l: 'Multiplicador por cascada', t: 'list', g: 'Cascadas', help: 'Uno por cada caída; el último se repite.' },
    MAXWIN,
  ],
  megaways: [
    WEIGHTED('rowWeights', 'Filas por rodillo (probabilidad)', 'Rodillos', [{ k: 'rows', l: 'Filas', t: 'int', min: 2, max: 7 }]),
    { k: 'wildMultMin', l: 'Comodines necesarios para multiplicar', t: 'int', min: 0, max: 10, g: 'Multiplicadores', help: '0 = apagado. Con esa cantidad o más, cada comodín suma +1 al multiplicador del giro.' },
    MULTS(),
    { k: 'scattersToTrigger', l: 'Scatters para giros gratis', t: 'int', min: 2, max: 6, g: 'Giros gratis' },
    { k: 'freeSpinsPerScatter', l: 'Giros por cada scatter', t: 'int', min: 0, max: 30, g: 'Giros gratis', help: '0 = usar la tabla de abajo.' },
    { k: 'freeSpins', l: 'Tabla scatters → giros', t: 'kv', kl: 'Scatters', vl: 'Giros', g: 'Giros gratis' },
    { k: 'retrigger', l: 'Giros extra al reactivar', t: 'int', min: 0, max: 50, g: 'Giros gratis' },
    { k: 'fsMultiplierStep', l: 'El multiplicador sube por giro ganador', t: 'num', min: 0, max: 5, step: 0.1, g: 'Giros gratis' },
    MAXWIN,
  ],
  'megaways-cascade': [
    WEIGHTED('rowWeights', 'Filas por rodillo (probabilidad)', 'Rodillos', [{ k: 'rows', l: 'Filas', t: 'int', min: 2, max: 7 }]),
    { k: 'cascadeStep', l: 'El multiplicador sube por cascada', t: 'num', min: 0, max: 5, step: 0.1, g: 'Cascadas' },
    { k: 'wildMultMin', l: 'Comodines necesarios para multiplicar', t: 'int', min: 0, max: 10, g: 'Cascadas', help: '0 = apagado. Cada comodín suma +1 al multiplicador de esa caída.' },
    WEIGHTED('mysteryWeights', 'Símbolo MISTERIO se revela como', 'Misterio', [{ k: 'symbol', l: 'Símbolo', t: 'symbol' }]),
    { k: 'scattersToTrigger', l: 'Scatters para giros gratis', t: 'int', min: 2, max: 6, g: 'Giros gratis' },
    { k: 'freeSpins', l: 'Giros gratis', t: 'int', min: 1, max: 100, g: 'Giros gratis' },
    { k: 'extraSpinsPerScatter', l: 'Giros extra por scatter adicional', t: 'int', min: 0, max: 30, g: 'Giros gratis' },
    { k: 'retriggerScatters', l: 'Scatters para reactivar', t: 'int', min: 2, max: 6, g: 'Giros gratis' },
    { k: 'retrigger', l: 'Giros extra al reactivar', t: 'int', min: 0, max: 50, g: 'Giros gratis' },
    { k: 'fsKeepMultiplier', l: 'El multiplicador no se reinicia en giros gratis', t: 'bool', g: 'Giros gratis' },
    MAXWIN,
  ],
  'bonus-buy': [
    { k: 'freeSpins', l: 'Scatters → giros gratis', t: 'kv', kl: 'Scatters', vl: 'Giros', g: 'Giros gratis' },
    { k: 'fsMultiplier', l: 'Multiplicador de los giros gratis', t: 'num', min: 1, max: 20, step: 0.5, g: 'Giros gratis' },
    { k: 'retrigger', l: 'Giros extra al reactivar', t: 'int', min: 0, max: 50, g: 'Giros gratis' },
    { k: 'maxFreeSpins', l: 'Máximo de giros gratis', t: 'int', min: 5, max: 200, g: 'Giros gratis' },
    { k: 'fsStickyRandom', l: 'Wilds fijos al azar al empezar', t: 'int', min: 0, max: 8, g: 'Giros gratis' },
    { k: 'fsExtraChance', l: 'Probabilidad de giros extra por giro', t: 'pct', min: 0, max: 0.5, step: 0.01, g: 'Giros gratis' },
    { k: 'fsExtraSpins', l: 'Giros extra que da', t: 'int', min: 1, max: 20, g: 'Giros gratis' },
    { k: 'fsExtraMax', l: 'Veces por bonus (0 = sin límite)', t: 'int', min: 0, max: 20, g: 'Giros gratis' },
    { k: 'randomBonusChance', l: 'Probabilidad de BONUS SORPRESA por giro', t: 'pct', min: 0, max: 0.2, step: 0.001, g: 'Bonus sorpresa' },
    { k: 'randomBonuses', l: 'Bonus que pueden salir de sorpresa', t: 'multi', o: [['free', 'Giros gratis'], ['pick', 'Elige un premio'], ['wheel', 'Ruleta'], ['collect', 'Colecciona'], ['path', 'El camino']], g: 'Bonus sorpresa' },
    BUY(),
    { k: 'bonusMenu.pick.enabled', l: 'Activo', t: 'bool', g: 'Bonus: Elige un premio' },
    { k: 'bonusMenu.pick.name', l: 'Nombre', t: 'text', g: 'Bonus: Elige un premio' },
    { k: 'bonusMenu.pick.cost', l: 'Precio (× la apuesta)', t: 'num', min: 1, step: 0.01, g: 'Bonus: Elige un premio' },
    { k: 'bonusMenu.pick.tiles', l: 'Casillas', t: 'int', min: 2, max: 30, g: 'Bonus: Elige un premio' },
    { k: 'bonusMenu.pick.picks', l: 'Elecciones', t: 'int', min: 1, max: 20, g: 'Bonus: Elige un premio' },
    { k: 'bonusMenu.pick.valueMin', l: 'Premio mínimo (× la apuesta)', t: 'num', min: 0, step: 0.01, g: 'Bonus: Elige un premio' },
    { k: 'bonusMenu.pick.valueMax', l: 'Premio máximo (× la apuesta)', t: 'num', min: 0, step: 0.01, g: 'Bonus: Elige un premio' },
    { k: 'bonusMenu.pick.bonusChance', l: 'Casillas BONUS', t: 'pct', min: 0, max: 1, step: 0.01, g: 'Bonus: Elige un premio' },
    { k: 'bonusMenu.pick.bonusMult', l: 'Las BONUS valen ×', t: 'num', min: 1, max: 20, step: 0.5, g: 'Bonus: Elige un premio' },
    { k: 'bonusMenu.wheel.enabled', l: 'Activo', t: 'bool', g: 'Bonus: Ruleta' },
    { k: 'bonusMenu.wheel.name', l: 'Nombre', t: 'text', g: 'Bonus: Ruleta' },
    { k: 'bonusMenu.wheel.cost', l: 'Precio (× la apuesta)', t: 'num', min: 1, step: 0.01, g: 'Bonus: Ruleta' },
    { k: 'bonusMenu.wheel.spins', l: 'Giros de ruleta', t: 'int', min: 1, max: 20, g: 'Bonus: Ruleta' },
    { k: 'bonusMenu.wheel.multStep', l: 'El multiplicador sube por giro', t: 'num', min: 0, max: 5, step: 0.1, g: 'Bonus: Ruleta' },
    { k: 'bonusMenu.wheel.segmentsCount', l: 'Segmentos', t: 'int', min: 4, max: 24, g: 'Bonus: Ruleta' },
    { k: 'bonusMenu.wheel.valueMin', l: 'Valor mínimo (× la apuesta)', t: 'num', min: 0, step: 0.01, g: 'Bonus: Ruleta' },
    { k: 'bonusMenu.wheel.valueMax', l: 'Valor máximo (× la apuesta)', t: 'num', min: 0, step: 0.01, g: 'Bonus: Ruleta' },
    { k: 'bonusMenu.collect.enabled', l: 'Activo', t: 'bool', g: 'Bonus: Colecciona' },
    { k: 'bonusMenu.collect.name', l: 'Nombre', t: 'text', g: 'Bonus: Colecciona' },
    { k: 'bonusMenu.collect.cost', l: 'Precio (× la apuesta)', t: 'num', min: 1, step: 0.01, g: 'Bonus: Colecciona' },
    { k: 'bonusMenu.collect.items', l: 'Objetos', t: 'int', min: 3, max: 40, g: 'Bonus: Colecciona' },
    { k: 'bonusMenu.collect.valueMin', l: 'Valor mínimo (× la apuesta)', t: 'num', min: 0, step: 0.01, g: 'Bonus: Colecciona' },
    { k: 'bonusMenu.collect.valueMax', l: 'Valor máximo (× la apuesta)', t: 'num', min: 0, step: 0.01, g: 'Bonus: Colecciona' },
    { k: 'bonusMenu.path.enabled', l: 'Activo', t: 'bool', g: 'Bonus: El camino' },
    { k: 'bonusMenu.path.name', l: 'Nombre', t: 'text', g: 'Bonus: El camino' },
    { k: 'bonusMenu.path.cost', l: 'Precio (× la apuesta)', t: 'num', min: 1, step: 0.01, g: 'Bonus: El camino' },
    { k: 'bonusMenu.path.length', l: 'Casillas del camino', t: 'int', min: 5, max: 40, g: 'Bonus: El camino' },
    { k: 'bonusMenu.path.valueStep', l: 'Cada casilla paga (posición ×)', t: 'num', min: 0, step: 0.01, g: 'Bonus: El camino' },
    { k: 'bonusMenu.path.stepMin', l: 'Dado: mínimo', t: 'int', min: 1, max: 6, g: 'Bonus: El camino' },
    { k: 'bonusMenu.path.stepMax', l: 'Dado: máximo', t: 'int', min: 1, max: 12, g: 'Bonus: El camino' },
    { k: 'bonusMenu.path.multStep', l: 'El multiplicador sube por tirada', t: 'num', min: 0, max: 2, step: 0.05, g: 'Bonus: El camino' },
    { k: 'bonusMenu.sticky.enabled', l: 'Activo', t: 'bool', g: 'Bonus: Wilds fijos' },
    { k: 'bonusMenu.sticky.name', l: 'Nombre', t: 'text', g: 'Bonus: Wilds fijos' },
    { k: 'bonusMenu.sticky.cost', l: 'Precio (× la apuesta)', t: 'num', min: 1, step: 0.01, g: 'Bonus: Wilds fijos' },
    { k: 'bonusMenu.sticky.freeSpins', l: 'Giros gratis', t: 'int', min: 1, max: 100, g: 'Bonus: Wilds fijos' },
    MAXWIN,
  ],
  'hold-win': [
    { k: 'triggerCount', l: 'Monedas para activar el bonus', t: 'int', min: 3, max: 30, g: 'Bonus' },
    { k: 'holdMode', l: 'Tipo de bonus', t: 'select', o: [['pick', 'ELIGE Y FIJA (el jugador elige)'], ['auto', 'Re-giros clásicos']], g: 'Bonus' },
    WEIGHTED('coinValues', 'Monedas (nivel, valor y probabilidad)', 'Monedas', [{ k: 'name', l: 'Nivel', t: 'text' }, { k: 'value', l: 'Valor ×', t: 'num', min: 0, step: 0.01 }, { k: 'jackpot', l: 'Jackpot', t: 'text', help: 'mini, minor o major' }]),
    { k: 'jackpots.mini', l: 'Jackpot MINI (× la apuesta)', t: 'num', min: 0, step: 0.1, g: 'Jackpots' },
    { k: 'jackpots.minor', l: 'Jackpot MINOR', t: 'num', min: 0, step: 0.1, g: 'Jackpots' },
    { k: 'jackpots.major', l: 'Jackpot MAJOR', t: 'num', min: 0, step: 0.1, g: 'Jackpots' },
    { k: 'jackpots.grand', l: 'Jackpot GRAND (pantalla llena)', t: 'num', min: 0, step: 0.1, g: 'Jackpots' },
    { k: 'rounds', l: 'Rondas del bonus', t: 'int', min: 1, max: 10, g: 'Elige y fija', when: { holdMode: 'pick' } },
    { k: 'candidatesMin', l: 'Monedas misteriosas por ronda: mínimo', t: 'int', min: 1, max: 10, g: 'Elige y fija', when: { holdMode: 'pick' } },
    { k: 'candidatesMax', l: 'Monedas misteriosas por ronda: máximo', t: 'int', min: 1, max: 10, g: 'Elige y fija', when: { holdMode: 'pick' } },
    { k: 'injectSpecials', l: 'Especiales extra en la primera ronda', t: 'int', min: 0, max: 5, g: 'Elige y fija', when: { holdMode: 'pick' } },
    { k: 'holdGrowth', l: 'Las monedas fijas crecen al fijar otra', t: 'pct', min: 0, max: 0.5, step: 0.01, g: 'Elige y fija', when: { holdMode: 'pick' } },
    { k: 'specialChance', l: 'Probabilidad de especial', t: 'pct', min: 0, max: 0.99, step: 0.01, g: 'Elige y fija' },
    { k: 'pickSpecials', l: 'Especiales', t: 'table', g: 'Elige y fija', when: { holdMode: 'pick' }, cols: [
      { k: 'type', l: 'Tipo', t: 'select', o: [['bonus', 'Bonus (premio)'], ['multiplier', 'Multiplicador'], ['jackpot', 'Jackpot'], ['reset', 'Reset de rondas'], ['extra_round', '+1 ronda']] },
      { k: 'min', l: 'Mín.', t: 'num', min: 0, step: 0.01 }, { k: 'max', l: 'Máx.', t: 'num', min: 0, step: 0.01 },
      { k: 'jackpot', l: 'Jackpot', t: 'text' }, { k: 'weight', l: 'Peso', t: 'num', min: 0.01, step: 0.01 }] },
    { k: 'jackpotCounts', l: 'Jackpot por posiciones fijas', t: 'table', g: 'Jackpots', when: { holdMode: 'pick' }, cols: [
      { k: 'count', l: 'Fijas', t: 'int', min: 1, max: 100 }, { k: 'jackpot', l: 'Jackpot', t: 'select', o: [['mini', 'MINI'], ['minor', 'MINOR'], ['major', 'MAJOR']] }] },
    { k: 'respins', l: 'Re-giros', t: 'int', min: 1, max: 10, g: 'Re-giros clásicos', when: { holdMode: 'auto' } },
    { k: 'landChance', l: 'Probabilidad de moneda por casilla', t: 'pct', min: 0.001, max: 0.5, step: 0.001, g: 'Re-giros clásicos', when: { holdMode: 'auto' } },
    { k: 'specialCoins', l: 'Monedas especiales', t: 'table', g: 'Re-giros clásicos', when: { holdMode: 'auto' }, cols: [
      { k: 'special', l: 'Tipo', t: 'select', o: [['multiplier', 'Multiplicador'], ['respin', '+1 re-giro']] }, { k: 'mult', l: '×', t: 'int', min: 2 }, { k: 'weight', l: 'Peso', t: 'num', min: 0.01 }] },
    MAXWIN,
  ],
  'colossal-reels': [
    { k: 'colossalChance', l: 'Probabilidad de símbolo colosal por giro', t: 'pct', min: 0, max: 1, step: 0.01, g: 'Colosales' },
    WEIGHTED('colossalSizes', 'Tamaños', 'Colosales', [{ k: 'size', l: 'Tamaño', t: 'select', o: [[2, '2x2'], [3, '3x3'], [4, '4x4']] }]),
    WEIGHTED('colossalSymbols', 'Símbolo colosal', 'Colosales', [{ k: 'symbol', l: 'Símbolo', t: 'symbol' }]),
    { k: 'fsColossalChance', l: 'Colosal en giros gratis', t: 'pct', min: 0, max: 1, step: 0.05, nullable: true, g: 'Giros gratis', help: 'Vacío = siempre (100 %).' },
    { k: 'freeSpins', l: 'Scatters → giros gratis', t: 'kv', kl: 'Scatters', vl: 'Giros', g: 'Giros gratis' },
    { k: 'retrigger', l: 'Giros extra al reactivar', t: 'int', min: 0, max: 50, g: 'Giros gratis' },
    MAXWIN,
  ],
  'cluster-pays': [
    { k: 'minCluster', l: 'Tamaño mínimo de grupo', t: 'int', min: 3, max: 10, g: 'Grupos' },
    { k: 'cascadeMultipliers', l: 'Multiplicador por cascada', t: 'list', g: 'Grupos', help: 'Uno por cada caída; el último se repite.' },
    { k: 'spotStart', l: 'Casillas doradas: primer multiplicador', t: 'int', min: 0, max: 10, g: 'Casillas doradas', help: '0 = apagado. Se duplica en cada explosión.' },
    { k: 'spotMax', l: 'Casillas doradas: multiplicador máximo', t: 'int', min: 2, max: 1024, g: 'Casillas doradas' },
    { k: 'scattersToTrigger', l: 'Scatters para giros gratis', t: 'int', min: 2, max: 10, g: 'Giros gratis' },
    { k: 'freeSpins', l: 'Scatters → giros gratis', t: 'kv', kl: 'Scatters', vl: 'Giros', g: 'Giros gratis' },
    { k: 'retrigger', l: 'Giros extra al reactivar', t: 'int', min: 0, max: 50, g: 'Giros gratis' },
    { k: 'fsKeepSpots', l: 'Las casillas doradas no se borran en giros gratis', t: 'bool', g: 'Giros gratis' },
    BUY(),
    MAXWIN,
  ],
  'scatter-pays': [
    MULTS('multiplierValues', 'Bombas multiplicadoras', 'Bombas'),
    { k: 'zeusChance', l: 'Rayo de Zeus: probabilidad por giro', t: 'pct', min: 0, max: 0.5, step: 0.001, g: 'Rayo de Zeus' },
    { k: 'zeusOrbsMin', l: 'Bombas extra: mínimo', t: 'int', min: 1, max: 10, g: 'Rayo de Zeus' },
    { k: 'zeusOrbsMax', l: 'Bombas extra: máximo', t: 'int', min: 1, max: 10, g: 'Rayo de Zeus' },
    { k: 'scattersToTrigger', l: 'Scatters para giros gratis', t: 'int', min: 3, max: 8, g: 'Giros gratis' },
    { k: 'freeSpins', l: 'Giros gratis', t: 'int', min: 1, max: 100, g: 'Giros gratis' },
    { k: 'retriggerScatters', l: 'Scatters para reactivar', t: 'int', min: 2, max: 8, g: 'Giros gratis' },
    { k: 'retrigger', l: 'Giros extra al reactivar', t: 'int', min: 0, max: 50, g: 'Giros gratis' },
    BUY('El precio se recalcula al pulsar «Ajustar RTP».'),
    ...ANTE,
    MAXWIN,
  ],
  'expanding-symbol': [
    { k: 'scattersToTrigger', l: 'Libros para giros gratis', t: 'int', min: 2, max: 5, g: 'Giros gratis' },
    { k: 'freeSpins', l: 'Giros gratis', t: 'int', min: 1, max: 100, g: 'Giros gratis' },
    { k: 'secondSpecial', l: 'Al reactivar, segundo símbolo especial', t: 'bool', g: 'Giros gratis' },
    WEIGHTED('expandWeights', 'Símbolo especial (probabilidad)', 'Símbolo especial', [{ k: 'symbol', l: 'Símbolo', t: 'symbol' }]),
    { k: 'frameChance', l: 'Marco multiplicador: probabilidad por giro', t: 'pct', min: 0, max: 1, step: 0.01, g: 'Marcos multiplicadores' },
    MULTS('frameValues', 'Valores del marco', 'Marcos multiplicadores'),
    ...ANTE,
    MAXWIN,
  ],
  'sticky-wilds': [
    { k: 'wildMode', l: 'Comodines', t: 'select', o: [['sticky', 'Fijos en giros gratis'], ['walking', 'Caminantes (dan re-giros)']], g: 'Comodines' },
    { k: 'scattersToTrigger', l: 'Scatters para giros gratis', t: 'int', min: 2, max: 5, g: 'Giros gratis' },
    { k: 'freeSpins', l: 'Giros gratis', t: 'int', min: 1, max: 100, g: 'Giros gratis' },
    { k: 'fsMultiplier', l: 'Multiplicador de los giros gratis', t: 'num', min: 1, max: 20, step: 0.5, g: 'Giros gratis' },
    { k: 'retrigger', l: 'Giros extra al reactivar', t: 'int', min: 0, max: 50, g: 'Giros gratis' },
    { k: 'maxFreeSpins', l: 'Máximo de giros gratis', t: 'int', min: 5, max: 200, g: 'Giros gratis' },
    { k: 'fsStickyRandom', l: 'Comodines al azar al empezar', t: 'int', min: 0, max: 8, g: 'Giros gratis' },
    { k: 'fsExtraChance', l: 'Probabilidad de giros extra por giro', t: 'pct', min: 0, max: 0.5, step: 0.01, g: 'Giros gratis' },
    { k: 'fsExtraSpins', l: 'Giros extra que da', t: 'int', min: 1, max: 20, g: 'Giros gratis' },
    { k: 'fsExtraMax', l: 'Veces por bonus (0 = sin límite)', t: 'int', min: 0, max: 20, g: 'Giros gratis' },
    MAXWIN,
  ],
  'treasure-chests': [
    { k: 'triggerCount', l: 'Cofres para el bonus', t: 'int', min: 2, max: 5, g: 'Cofres' },
    { k: 'triggerRow', l: 'Fila donde cuentan los cofres', t: 'int', min: -1, max: 7, g: 'Cofres', help: '0 = fila de arriba, 1 = la segunda… · -1 = en toda la pantalla.' },
    { k: 'chests', l: 'Cofres para elegir', t: 'int', min: 2, max: 6, g: 'Cofres' },
    WEIGHTED('chestPrizes', 'Premio de los cofres', 'Cofres', [{ k: 'mult', l: 'Multiplicador ×', t: 'num', min: 1, step: 0.5 }]),
    { k: 'chestMultTarget', l: 'El cofre multiplica', t: 'select', o: [['trigger', 'El premio del giro que lo activó'], ['freeSpins', 'Los giros gratis']], g: 'Cofres' },
    { k: 'freeSpins', l: 'Giros gratis', t: 'int', min: 1, max: 100, g: 'Giros gratis' },
    { k: 'retrigger', l: 'Giros extra al reactivar', t: 'int', min: 0, max: 50, g: 'Giros gratis' },
    { k: 'maxFreeSpins', l: 'Máximo de giros gratis', t: 'int', min: 5, max: 200, g: 'Giros gratis' },
    BUY(),
    MAXWIN,
  ],
  'level-up': [
    { k: 'maxLevel', l: 'Niveles', t: 'int', min: 2, max: 100, g: 'Niveles' },
    { k: 'xpBase', l: 'XP para pasar del nivel 1', t: 'int', min: 1, max: 100000, g: 'Niveles' },
    { k: 'xpGrowth', l: 'Cada nivel pide × más XP', t: 'num', min: 1, max: 3, step: 0.05, g: 'Niveles' },
    { k: 'xpPerSpin', l: 'XP por giro', t: 'int', min: 0, max: 1000, g: 'Niveles' },
    { k: 'rewards', l: 'Recompensas por nivel', t: 'table', g: 'Recompensas', help: 'Multiplicador: premios de línea × valor desde ese nivel. Semilla dorada: desde ese nivel. Jackpot: valor × la apuesta y vuelve al nivel 1.', cols: [
      { k: 'level', l: 'Nivel', t: 'int', min: 2, max: 100 },
      { k: 'type', l: 'Recompensa', t: 'select', o: [['multiplier', 'Multiplicador'], ['goldenSeed', 'Semillas doradas'], ['jackpot', 'Jackpot']] },
      { k: 'value', l: 'Valor', t: 'num', min: 0, step: 0.05 }] },
    { k: 'collectTarget', l: 'Semillas para subir un nivel (0 = sin colección)', t: 'int', min: 0, max: 1000, g: 'Drop & Collect' },
    { k: 'triggerCount', l: 'Semillas para el bonus de cofres', t: 'int', min: 2, max: 6, g: 'Bonus de cofres' },
    WEIGHTED('pickValues', 'Premios de los cofres (× la apuesta)', 'Bonus de cofres', [{ k: 'value', l: 'Premio ×', t: 'num', min: 0, step: 0.01 }]),
    { k: 'bonusXpBase', l: 'XP del bonus (fijo)', t: 'int', min: 0, max: 10000, g: 'Bonus de cofres' },
    { k: 'bonusXpPerValue', l: 'XP del bonus por cada × de premio', t: 'int', min: 0, max: 1000, g: 'Bonus de cofres' },
    { k: 'bonusLevelUp', l: 'El bonus sube un nivel', t: 'bool', g: 'Bonus de cofres' },
    { k: 'goldenChance', l: 'Probabilidad de semilla dorada', t: 'pct', min: 0, max: 1, step: 0.01, g: 'Semillas doradas' },
    { k: 'goldenMult', l: 'La semilla dorada multiplica el cofre ×', t: 'num', min: 1, max: 20, step: 0.5, g: 'Semillas doradas' },
    MAXWIN,
  ],
  'classic-reels': [
    { k: 'lines', l: 'Líneas (1 a 5)', t: 'int', min: 1, max: 5, g: 'Líneas', help: '1 = central · 3 = las tres filas · 5 = filas y diagonales.' },
    { k: 'anyBarPay', l: '«Cualquier BAR» paga (× apuesta por línea)', t: 'num', min: 0, step: 0.01, g: 'Premios' },
    { k: 'wildMult', l: 'El comodín multiplica ×', t: 'num', min: 1, max: 10, step: 0.5, g: 'Comodín', help: 'Dos comodines en la línea: el multiplicador al cuadrado.' },
    { k: 'multReel.enabled', l: 'Rodillo multiplicador', t: 'bool', g: 'Rodillo multiplicador' },
    MULTS('multReel.values', 'Valores del rodillo multiplicador', 'Rodillo multiplicador'),
    MAXWIN,
  ],
  'cash-collect': [
    WEIGHTED('coinValues', 'Valores de las monedas (× la apuesta)', 'Monedas', [{ k: 'value', l: 'Valor ×', t: 'num', min: 0, step: 0.01 }]),
    { k: 'triggerCount', l: 'Scatters para giros gratis', t: 'int', min: 2, max: 5, g: 'Giros gratis' },
    { k: 'freeSpins', l: 'Giros gratis', t: 'int', min: 1, max: 100, g: 'Giros gratis' },
    { k: 'maxFreeSpins', l: 'Máximo de giros gratis', t: 'int', min: 5, max: 200, g: 'Giros gratis' },
    { k: 'fsLevels', l: 'Niveles del recolector', t: 'table', g: 'Giros gratis', cols: [
      { k: 'collect', l: 'Recolectores', t: 'int', min: 1, max: 100 }, { k: 'spins', l: '+Giros', t: 'int', min: 0, max: 50 }, { k: 'mult', l: 'Monedas ×', t: 'num', min: 1, step: 0.5 }] },
    BUY(),
    MAXWIN,
  ],
};

/** Qué hace cada motor, para la ficha de elección (el resto sale de la semilla calibrada). */
export const ENGINE_CARDS = {
  'reel-rush': { grid: '5 rodillos que crecen', pays: 'Formas de ganar', bonus: 'Cascadas con multiplicador ×1 → ×8', features: ['Cada premio desbloquea más filas', 'Cascadas con multiplicador creciente'] },
  megaways: { grid: '6 rodillos de 2 a 7 filas', pays: 'Hasta 117.649 formas', bonus: '10 giros gratis por cada scatter', features: ['2+ comodines multiplican el giro', 'Símbolos multiplicador ×2 a ×25', 'Multiplicador que sube en giros gratis'] },
  'megaways-cascade': { grid: '6 rodillos de 2 a 7 filas', pays: 'Formas + cascadas', bonus: '30+ giros con multiplicador que no se reinicia', features: ['+0,5 al multiplicador por cascada', 'Comodines suman al multiplicador', 'Símbolos misterio'] },
  'bonus-buy': { grid: '5x3, 20 líneas', pays: 'Líneas', bonus: 'Giros ×2 con 3 wilds fijos + 4 minijuegos', features: ['BONUS SORPRESA en cualquier giro', 'Ruleta, Elige, Colecciona y El camino', 'Menú de compra con precio por bono'] },
  'hold-win': { grid: '5x5, 20 líneas', pays: 'Líneas + monedas', bonus: 'ELIGE Y FIJA con 4 jackpots', features: ['El jugador elige qué moneda fijar', 'Monedas Bronce a Diamante que crecen +10 %', 'Especiales: bonus, ×, jackpot, reset y +1 ronda'] },
  'colossal-reels': { grid: '5x4 con colosales', pays: 'Formas de ganar', bonus: 'Giros gratis con colosal garantizado', features: ['Símbolos colosales 2x2, 3x3 y 4x4', 'Sacudida de pantalla'] },
  'cluster-pays': { grid: '7x7', pays: 'Grupos de 5+ iguales', bonus: 'Giros gratis con casillas doradas que no se borran', features: ['Casillas doradas ×2 → ×32', 'Cascadas con multiplicador', 'Compra del bonus'] },
  'scatter-pays': { grid: '6x5', pays: '8+ iguales en cualquier lugar', bonus: '15 giros con multiplicador acumulado', features: ['Bombas ×2 a ×100', 'Rayo de Zeus: bombas extra al azar', 'Doble chance y compra del bonus'] },
  'expanding-symbol': { grid: '5x3, 10 líneas', pays: 'Líneas', bonus: 'Giros gratis con símbolo que se expande', features: ['El libro elige el símbolo especial', 'Segundo especial al reactivar', 'Marcos multiplicadores y doble chance'] },
  'sticky-wilds': { grid: '5x3, 9 líneas', pays: 'Líneas', bonus: '10 giros ×2 con comodines fijos', features: ['3 comodines fijos al azar al empezar', '+5 giros al azar', 'Modo comodines caminantes'] },
  'treasure-chests': { grid: '5x4', pays: '3, 4 o 5 iguales en una fila', bonus: 'Cofres que multiplican el premio', features: ['Elige 1 de 3 cofres (×1, ×2, ×3)', 'Giros gratis con nuevos cofres'] },
  'cash-collect': { grid: '5x3, 10 líneas', pays: 'Líneas + monedas', bonus: 'Giros gratis con niveles del recolector', features: ['Monedas con premio en dinero', 'El recolector cobra todas las monedas', 'Niveles: más giros y monedas ×2, ×3, ×5'] },
  'level-up': { grid: '5x3, 10 líneas', pays: 'Líneas', bonus: 'Bonus de cofres y niveles con recompensas', features: ['El jugador sube de nivel (se guarda por apuesta)', 'Barra de XP y colección de semillas', 'Recompensas: multiplicador, semillas doradas y jackpot'] },
  'classic-reels': { grid: '3x3, 5 líneas', pays: 'Líneas clásicas', bonus: 'Rodillo multiplicador ×1 a ×10', features: ['Frutas, BAR y 7 de toda la vida', 'Cerezas que pagan desde una', 'Comodín ×2 (dos comodines ×4)', 'Cualquier BAR paga'] },
  craps: { grid: 'Mesa de dados', pays: 'Apuestas de mesa', bonus: '—', features: ['Pass, Come, Odds, Field, Hardways', 'Lanzamiento arrastrando con potencia', 'RTP exacto por apuesta'] },
};
